build(packaging): Update nodejs and npm versions
Azure/static-web-apps-cli pull request #424
Opened 2022-03-29 11:08 UTC by Devansu-Yadav

Update Nodejs and NPM to the LTS versions in the Github workflow as well as for build since Nodejs 14 LTS is going to be deprecated.

Output of `Jest` tests using the `npm test` command:

![Issue #394 npm test output](https://user-images.githubusercontent.com/62554685/160598099-0d06e377-3251-4960-beb4-41433de86e10.png)

Output of Cypress test using `npm e2e:static` command:

![Issue #394 e2e static Cypress test output](https://user-images.githubusercontent.com/62554685/160598185-1bf7cfaa-8fa1-4021-981f-43cb81148e5d.png)

Closes #394

2022-03-30 10:08 UTC, manekinekko approved these changes

2022-03-30 12:44 UTC, sinedied requested changes

2022-03-30 12:44 UTC, sinedied commented on package.json
> +    "node": ">=16.0.0",
It's fine if we target node 16 for our dev/release workflow, but we shouldn't stop support for node 14 right away as a lot of people are still relying on it and it's also a supported runtime for SWA and Functions.

Our test suite runs starting from Node 12+, so as long as we don't have a blocking issue for supporting older Node version I'd suggest that we keep supporting at least all runtimes supported by SWA, ie Node >= 14 IIRC

2022-04-08 08:23 UTC, Devansu-Yadav commented
@manekinekko @sinedied I hope this PR resolves this issue. Please let me know if any changes are required.

2022-04-08 09:38 UTC, sinedied approved these changes

2022-04-08 09:57 UTC, manekinekko approved these changes

2022-04-22 13:11 UTC, manekinekko commented
Thank you @Devansu-Yadav for your great contribution. Your PR is scheduled to be merged as soon as we finish adding the other major features, and merge them to the main branch.

2022-05-02 13:44 UTC, sinedied commented
Thanks for this PR @[Devansu-Yadav](https://github.com/Devansu-Yadav)! Would it be possible for you to revert your changes in package-lock.json, as it will cause issues for merging it?

2022-05-02 15:32 UTC, Devansu-Yadav commented
> Thanks for this PR @[Devansu-Yadav](https://github.com/Devansu-Yadav)! Would it be possible for you to revert your changes in package-lock.json, as it will cause issues for merging it?

I have reverted the changes in the file 👍

2022-05-06 06:43 UTC, merged